version: '3'
services:
  cmt-telegram-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      WEBHOOK_URL: "${WEBHOOK_URL}"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - cmt-telegram-bot
    networks:
      - webnet

networks:
  webnet:
